services:
  app:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-frontend-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      # initialize database with some data 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-mongo

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    # persist data by declaring volume here
    volumes:
      - redis_data:/data
    container_name: todo-redis

  server:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-backend-dev
    environment:
      - REDIS_URL=redis://todo-redis:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-mongo:27017/the_database
  debug-helper:
    image: busybox

volumes:
  mongo_data:
  redis_data: